# Generated by Django 4.2.7 on 2024-01-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_retetecuverdeturi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='available_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_grams',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
